### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by IRediTOTO** [bentzibentz/tailwindcss-animate.css#16]
Hello, I am trying minify CSS with purgecss, but something wrong. 
Css file still get up to >2000 lines :c 
In that file have there animate:
@-webkit-keyframes fadeOutUp {
  to {
      opacity: 0;
      transform: translate3d(0,-100%,0)
  }
}
It only come from this... I don't know how to fix.
![image](https://user-images.githubusercontent.com/15695252/79059064-b8c84b80-7c9f-11ea-97fb-143d127e12d7.png)

**Comment by bentzibentz** [comment]
you have to set the keyframes option to true at your purgecss configuration.

Have a look here: https://purgecss.com/configuration.html#options

**Comment by bentzibentz** [comment]
I close the issue, if problem still exist feel free to reopen it.
