### ISSUE TITLE
Prevent plugin from breaking when no object is passed

### ISSUE THREAD

**Issue by hacknug** [bentzibentz/tailwindcss-animate.css#17]
This would be a matter of providing an empty object as fallback.

Can open a PR with the changes if you want.

**Comment by bentzibentz** [comment]
Good idea.

Feel free to open a PR, I will merge it.

**Comment by bentzibentz** [comment]
I tested it with an empty settings object

`require('tailwindcss-animatecss')({
      settings: {},
      variants: ['responsive'],
    }),
`

it worked as expected, the fallback values are used.

Can you describe your problem a bit further?

**Comment by hacknug** [comment]
> I tested it with an empty settings object

Yeah, I meant prevent it from breaking when you pass absolutely nothing to the plugin. Right now it breaks because it tries to destructure `undefined` or `null` or something.

**Comment by bentzibentz** [comment]
Fixed in v3.0.0
