### ISSUE TITLE
Allow users to cherry pick animations in plugin config

### ISSUE THREAD

**Issue by hacknug** [bentzibentz/tailwindcss-animate.css#18]
So instead of always generating classes for everything in `animate.css`, I'd like to be able to pass an array of animations (or animation groups aka the labels used for `optgroup`'s on Animate.css' website).

This would reduce the CSS bloat when not using PurgeCSS (can't use it on this site I'm working on for reasons) and help avoid possible name collissions in case the codebase already includes a given classname.

**Comment by bentzibentz** [comment]
I've been thinking about that, too. As soon as I have a little more time, I'll take a look at it. Meanwhile feel free to open a PR if you want to integrate it.

**Comment by bentzibentz** [comment]
So I added a fix version of this idea. You can now define a classes array at the plugin options to define which classes and are generated.

Just have a look at the updated docs. 

I look forward to your opinion.

**Comment by bentzibentz** [comment]
Issue closed, feel free to reopen if it doesn't suit your needs
