### ISSUE TITLE
Add `prefix` option to plugin config to namespace generated classes

### ISSUE THREAD

**Issue by hacknug** [bentzibentz/tailwindcss-animate.css#20]
This would help avoid possible name collisions in case the codebase already includes a given classname.

**Comment by bentzibentz** [comment]
It's already in development, I'll publish it the days.

**Comment by bentzibentz** [comment]
If you setup the tailwind prefix option like:

```js
// tailwind.config.js
module.exports = {
  prefix: 'tw-',
  // ...
}
```
the plugin classes are prefixed.

**Comment by bentzibentz** [comment]
Issue closed, feel free to reopen if it doesn't suit your needs.
