### ISSUE TITLE
Add plugin option to support `prefers-reduced-motion`

### ISSUE THREAD

**Issue by hacknug** [bentzibentz/tailwindcss-animate.css#21]
CSS allows you to detect if users have decided to opt-out of motion-related stuff. Would be cool if there was an option to wrap the generated CSS into a mediaquery checking for this.

This is important for accessibility reasons.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by bentzibentz** [comment]
I will have a look at this soon.

**Comment by bentzibentz** [comment]
Added it right now, just add 'reduced-motion' to the variants array at the plugin settings.
