### ISSUE TITLE
Why this plugin?

### ISSUE THREAD

**Issue by frederikhors** [bentzibentz/tailwindcss-animate.css#26]
Can I ask you why this plugin?

What if I simply add `animate.css` to my project?

Example:

_index.css_:

```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@import "animate.css/animate";
```

_index.html_:

```html
<div class="animate__animated animate__bounce">The div</div>
```

What is the use of your plugin?

**Comment by bentzibentz** [comment]
The reason I build this is I love to work with tailwind and having fun to build it.

The best thing about plugins is you don’t have to use them. 

So feel free not to use it.

**Comment by frederikhors** [comment]
Oh, I see. Thanks. Just curiosity. Don't take it negative.
