### ISSUE TITLE
Not found class name with @tailwindcssinjs/macro

### ISSUE THREAD

**Issue by IRediTOTO** [bentzibentz/tailwindcss-animate.css#29]
Hi, im using @tailwindcssinjs/macro with tailwindcss-animate.css
I have this code
```tw`shadow-md rounded  nm-flat-gray-200-lg animate__animated animate__fadeInLeft```
It's work well without animate class name. I use other plugin is tailwindcss-neumorphism, it work ok with no error.
Can you do something to make them work together, Thank you :D

**Comment by bentzibentz** [comment]
Closed due to inactivity
