### ISSUE TITLE
Tailwind 1.0 Support

### ISSUE THREAD

**Issue by daronspence** [bentzibentz/tailwindcss-animate.css#4]
I tried using the plugin with Tailwind v1.0 and it doesn't seem to be working.

Here is my `tailwind.config.js`

```
plugins: [
    require('tailwindcss-animatecss'),
]
```

When I tried it with your docs example, it was erroring out.

Thoughts?

**Comment by bentzibentz** [comment]
Hi,

the plugin is not ready for tailwind 1.0, i've been working on it, but because of the lack of time it takes some days.

**Comment by bentzibentz** [comment]
It works now with tailwind >= 1.0.0
